#define MASTER_RIGHT
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3360
POINTING_DEVICE_RIGHT = yes

# OLED_ENABLE = yes
# OLED_DRIVER = ssd1306
# OLED_TRANSPORT = i2c

SPLIT_KEYBOARD = yes
SERIAL_DRIVER = vendor